pagina/pagina/urls.py
from django.contrib import admin
from django.urls import path
from app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='inicio'),
    path('registro/', views.register, name='registro'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('solicitar_cita/', views.solicitar_cita, name='solicitar_cita'),
    path('cancelar_cita/<int:cita_id>/', views.cancelar_cita_admin, name='cancelar_cita_admin'),
    path('cancelar_cita_cliente/<int:cita_id>/', views.cancelar_cita_cliente, name='cancelar_cita_cliente'),
    path('citas/editar/<int:cita_id>/', views.editar_cita_cliente, name='editar_cita_cliente'),
    path('mis_citas/', views.mis_citas, name='mis_citas'),
    path('confirmar_cita/<int:cita_id>/', views.confirmar_cita, name='confirmar_cita'),
    path('tatuadores/',views.tatuadores,name='tatuadores'),
    path('citas/',views.lista_citas,name='citas'),
    path('terminos/', views.terminos, name='terminos'),
    path('privacidad/', views.privacidad, name='privacidad'),
    path('eliminar_tatuador/<int:tatuador_id>/', views.eliminar_tatuador, name='eliminar_tatuador'),
    path('editar_tatuador/<int:tatuador_id>/', views.editar_tatuador, name='editar_tatuador'),
    path('agregar_tatuador/', views.agregar_tatuador, name='agregar_tatuador'),
    path('agregar_cliente/', views.agregar_cliente, name='agregar_cliente'),
    path('agregar_cita/', views.agregar_cita, name='agregar_cita'),
    path('contactanos/', views.contactanos, name='contactanos'),
]

pagina/app/models.py
from django.db import models
from django.contrib.auth.models import User

class Tatuador(models.Model):
    OPCIONES_DISPONIBILIDAD = [
        ('Disponible', 'Disponible'),
        ('No disponible', 'No disponible')
    ]
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    tatuador_id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30, null=True)
    especialidad = models.CharField(max_length=30, null=True)
    disponibilidad = models.CharField(max_length=20, choices=OPCIONES_DISPONIBILIDAD, default='Disponible')
    telefono = models.DecimalField(max_digits=10, decimal_places=0, null=True)
    email = models.EmailField(max_length=255, null=True, unique=True)

    def __str__(self):
        return self.nombre

class Cliente(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    cliente_id = models.AutoField(primary_key=True)
    telefono = models.DecimalField(max_digits=10, decimal_places=0, null=True)
    email = models.EmailField(max_length=30, null=True, unique=True)
    nombre = models.CharField(max_length=40, null=True)

    def __str__(self):
        return self.nombre

class EstadoCita(models.Model):
    estado_id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=20)

    def __str__(self):
        return self.nombre

class Cita(models.Model):
    cita_id = models.AutoField(primary_key=True)
    fecha = models.DateField(null=True)
    hora = models.TimeField(null=True)
    estado = models.ForeignKey(EstadoCita, on_delete=models.SET_NULL, null=True)
    tatuador = models.ForeignKey(Tatuador, on_delete=models.CASCADE)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    
    def __str__(self):
        return f'Cita con {self.tatuador.nombre} para {self.cliente.nombre} el {self.fecha} a las {self.hora}'

pagina/app/forms.py
from django import forms
from app.models import Tatuador, Cliente, Cita
from django.contrib.auth.models import User
from datetime import datetime


class UserLoginForm(forms.Form):
    email = forms.EmailField(label='Email')
    password = forms.CharField(widget=forms.PasswordInput, label='Contraseña')


class TatuadorForm(forms.ModelForm):
    class Meta:
        model = Tatuador
        fields = ['nombre', 'especialidad', 'disponibilidad', 'telefono','email']

class EditarTatuadorForm(forms.ModelForm):
    class Meta:
        model = Tatuador
        fields = ['nombre', 'especialidad', 'disponibilidad', 'telefono', 'email']

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nombre', 'telefono']

class CitaForm(forms.ModelForm):
    class Meta:
        model = Cita
        fields = ['tatuador', 'fecha', 'hora']
        widgets={
            'fecha':forms.DateInput(attrs={'type':'date'}),
            'hora':forms.TimeInput(attrs={'type':'time'}),
        }
    

class AgregarCitaForm(forms.ModelForm):
    class Meta:
        model = Cita
        fields = ['tatuador','cliente','fecha', 'hora']
        widgets={
            'fecha':forms.DateInput(attrs={'type':'date'}),
            'hora':forms.TimeInput(attrs={'type':'time'}),
        }
    

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput, label='Confirmar Contraseña')

    class Meta:
        model = User
        fields = ['email']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError("¡Las contraseñas no coinciden!")

        return cleaned_data

class CitaFilterForm(forms.Form):
    fecha = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), initial=datetime.today)

pagina/app/templates/app/agregar_cita.html
{% extends 'app/index.html' %}

{% block content %}
<div class="form-container">
    <h2>Agregar Cita</h2>
    <form method="post">
        {% csrf_token %}
        
        <label for="id_tatuador">Tatuador:</label>
        {{ form.tatuador }}

        <label for="id_tatuador">Cliente:</label>
        {{ form.cliente }}

        <label for="id_fecha">Fecha:</label>
        {{ form.fecha }}

        <label for="id_hora">Hora:</label>
        {{ form.hora }}

        <button type="submit" class="login-button">Agregar Cita</button>
    </form>
</div>
{% endblock %}

pagina/app/templates/app/agregar_cliente.html
{% extends 'app/index.html' %}


{% block content %}
<div class="form-container">
    <h1 class="h1-form">Agregar Cliente</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="contact-button">Guardar</button>
    </form>
</div>
{% endblock %}

pagina/app/templates/app/agregar_tatuador.html
{% extends 'app/index.html' %}

{% block content %}
<div class="form-container">
    <h2>Registrar Tatuador</h2>
    <form method="post">
        {% csrf_token %}
        
        <div class="form-grid">
            <div class="form-group">
                <label for="id_nombre">Nombre:</label>
                {{ form.nombre }}
            </div>

            <div class="form-group">
                <label for="id_especialidad">Especialidad:</label>
                {{ form.especialidad }}
            </div>

            <div class="form-group">
                <label for="id_disponibilidad">Disponibilidad:</label>
                {{ form.disponibilidad }}
            </div>

            <div class="form-group">
                <label for="id_telefono">Teléfono:</label>
                {{ form.telefono }}
            </div>

            <div class="form-group">
                <label for="id_email">Email:</label>
                {{ form.email }}
            </div>

            <div class="form-group full-width">
                <button type="submit" class="contact-button">Registrar Tatuador</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

pagina/app/templates/app/citas.html
{% extends 'app/index.html' %}

{% block content %}
<div class="form-container">
    <h1 class="h1-form">Lista de Citas</h1>

    <form method="get" action="{% url 'citas' %}" class="filter-form">
        <label for="fecha">Seleccionar fecha:</label>
        <input type="date" name="fecha" value="{{ fecha_filtrada }}">
        <button type="submit" class="btn-filtrar">Filtrar</button>
        {% if fecha_filtrada %}
            <a href="{% url 'citas' %}" name="clear_filter" form="clear-filter-form" class="btn-eliminar-filtro">Borrar</a>
        {% endif %}
    </form>
    <table>
        <tr>
            <th>Fecha</th>
            <th>Hora</th>
            <th>Estado</th>
            <th>Cliente</th>
            <th>Acciones</th> 
        </tr>
        {% for cita in citas %}
            <tr>
                <td>{{ cita.fecha }}</td>
                <td>{{ cita.hora }}</td>
                <td>{{ cita.estado }}</td>
                <td>{{ cita.cliente.nombre }}</td>
                <td>
                    {% if cita.estado.nombre == "Solicitada" %}
                        {% if request.user.is_staff %}
                            <a href="{% url 'confirmar_cita' cita.cita_id %}">Confirmar</a>
                            <a href="{% url 'cancelar_cita_admin' cita_id=cita.cita_id %}">Cancelar</a>
                        {% endif %}
                    {% endif %}
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="6">No hay citas registradas.</td>
            </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

pagina/app/templates/app/contactanos.html
{% extends "app/index.html" %}

{% block content %}
    <div class="contact-container">
        <h1 class="h1-form">Contáctanos</h1>

        <div class="contact-form">
            <p class="contact-info">
                ¿Quieres ser parte de nuestro equipo? <br>
                <strong>Teléfono:</strong> +569 6841 6832 <br>
                <strong>Email:</strong> contacto@perlanegra.com <br>
                <strong>Ubicación:</strong> Coimbra 23, Copiapo, Chile  
            </p>

            <!-- Aquí puedes añadir el formulario si es necesario -->
            <form method="post" class="form-contact">
                {% csrf_token %}
                <div class="form-group">
                    <label for="name">Nombre</label>
                    <input type="text" id="nombre" name="nombre" required>
                </div>
                <div class="form-group">
                    <label for="email">Correo Electrónico</label>
                    <input type="email" id="email" name="email" required>
                </div>
                <div class="form-group">
                    <label for="message">Mensaje</label>
                    <textarea id="mensaje" name="mensaje" rows="4" required></textarea>
                </div>
                <button type="submit" class="contact-button">Enviar</button>
            </form>
        </div>
    </div>
{% endblock %}

pagina/app/templates/app/editar.html
{% extends 'app/index.html' %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="contact-button">Guardar cambios</button>
    </form>
{% endblock %}

pagina/app/templates/app/index.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Perla Negra</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'app/css/estilo.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/form.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/cita.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">
</head>
<body>
    <div class="container">
        <nav>
            <img src="{% static 'app/images/dragonblanco.png' %}" alt="logo-nav" class="logo-nav">
            <ul>
                <li><a href="{% url 'inicio' %}">Inicio</a></li>
                <li><a href="{% url 'tatuadores' %}">Tatuadores</a></li>

                {% if user.is_authenticated and not request.user.is_staff %}
                    <li><a href="{% url 'mis_citas' %}">Mis Citas</a></li>
                {% endif %}

                {% if request.user.is_staff and not user.is_superuser %}
                    <!-- Aquí ocultamos la sección de "Administrar Datos" para tatuadores -->
                    <li><a href="{% url 'citas' %}">Citas</a></li>
                {% endif %}

                {% if request.user.is_superuser %}
                    <!-- Solo los superusuarios pueden ver la sección de administrar datos -->
                    <li class="dropdown">
                        <a href="javascript:void(0)" class="dropbtn">Administrar Datos</a>
                        <div class="dropdown-content">
                            <a href="{% url 'agregar_tatuador' %}">Agregar Tatuador</a>
                            <a href="{% url 'agregar_cliente' %}">Agregar Cliente</a>
                            <a href="{% url 'agregar_cita' %}">Agregar Cita</a>
                        </div>
                    </li>
                    <li><a href="{% url 'citas' %}">Citas</a></li>
                {% endif %}

                {% if user.is_authenticated and not request.user.is_staff %}
                    <li><a href="{% url 'solicitar_cita' %}">Solicitar cita</a></li>
                {% endif %}

                <li><a href="{% url 'contactanos' %}">Contáctanos</a></li>

                {% if user.is_authenticated %}
                    <li class="user-info dropdown">
                        <span>Bienvenido, {{ user.username }}</span>
                        <div class="dropdown-content">
                            <form action="{% url 'logout' %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="logout-button">Cerrar Sesión</button>
                            </form>
                        </div>
                    </li>
                {% else %}
                    <li><a href="{% url 'login' %}">Iniciar Sesión</a></li>
                {% endif %}
            </ul>
        </nav>

        {% if request.path == '/' or request.path == '/index/' %}
            <img src="{% static 'app/images/dragonblanco.png' %}" alt="Logo" class="logo">
            <h1>
                <span>Perla</span>
                <span>Negra</span>
                <span>Ink</span>
            </h1>
        {% endif %}            

        {% block content %}
        {% endblock %}
    </div>

    {% if request.path == '/' or request.path == '/index/' %}
        <footer>
            <div class="footer-content">
                <p>&copy; {{ current_year }} Perla Negra Ink. Todos los derechos reservados.</p>
                <ul class="footer-links">
                    <li><a href="{% url 'terminos' %}">Términos del servicio</a></li>
                    <li><a href="{% url 'privacidad' %}">Política de privacidad</a></li>
                </ul>
            </div>
        </footer>
    {% endif %}
</body>
</html>

pagina/app/templates/app/mis_citas.html
{% extends 'app/index.html' %}

{% block content %}
<div class="form-container">
    <h2>Mis Citas</h2>

    <form method="get" action="{% url 'mis_citas' %}" class="filter-form">
        <label for="fecha">Seleccionar Fecha:</label>
        <input type="date" id="fecha" name="fecha" value="{{ fecha_filtrada|default:'' }}">

        <!-- Botón Filtrar -->
        <button type="submit" class="btn-filtrar">Filtrar</button>

        <!-- Botón para eliminar el filtro -->
        {% if fecha_filtrada %}
            <a href="{% url 'mis_citas' %}" name="clear_filter" form="clear-filter-form" class="btn-eliminar-filtro">Borrar</a>
        {% endif %}
    </form>

    <table>
        <thead>
            <tr>
                <th>Fecha</th>
                <th>Hora</th>
                <th>Estado</th>
                <th>Tatuador</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for cita in citas %}
            <tr>
                <td>{{ cita.fecha }}</td>
                <td>{{ cita.hora }}</td>
                <td>{{ cita.estado.nombre }}</td>
                <td>{{ cita.tatuador.nombre }} </td>
                <td>
                    {% if cita.estado.nombre != "Cancelada" %}
                        <form action="{% url 'cancelar_cita_cliente' cita.cita_id %}" method="post" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit">Cancelar</button>
                        </form>
                        <button onclick="document.getElementById('edit-form-{{ cita.cita_id }}').style.display='block'">Editar</button>
                        <div id="edit-form-{{ cita.cita_id }}" style="display:none;">
                            <form action="{% url 'editar_cita_cliente' cita.cita_id %}" method="post">
                                {% csrf_token %}
                                <label for="fecha">Nueva Fecha:</label>
                                <input type="date" name="fecha" value="{{ cita.fecha }}" required>
                                <label for="hora">Nueva Hora:</label>
                                <input type="time" name="hora" value="{{ cita.hora }}" required>
                                <button type="submit">Guardar</button>
                                <button type="button" onclick="document.getElementById('edit-form-{{ cita.cita_id }}').style.display='none'">Cancelar</button>
                            </form>
                        </div>
                    {% else %}
                        <span>Cita cancelada</span>
                    {% endif %}
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="4">No tienes citas solicitadas.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

pagina/app/templates/app/privacidad.html
{% extends 'app/index.html' %}

{% block content %}
<body>
    <div class="container-privacidad">
        <section>
            <h2>1. Introducción</h2>
            <p>En Perla Negra Ink, nos comprometemos a proteger su privacidad. Esta política explica cómo recopilamos, usamos y protegemos la información personal que nos proporciona.</p>

            <h2>2. Información Recopilada</h2>
            <p>Recopilamos información personal cuando usted realiza una cita, se registra en nuestra página, o se comunica con nosotros. La información que recopilamos puede incluir su nombre, dirección, correo electrónico, número de teléfono, fecha de nacimiento, y detalles del tatuaje solicitado.</p>

            <h2>3. Uso de la Información</h2>
            <p>Usamos su información personal para proporcionar y mejorar nuestros servicios, incluyendo la gestión de citas, la atención al cliente, y el envío de información relevante sobre nuestros servicios.</p>

            <h2>4. Compartir Información</h2>
            <p>No compartimos su información personal con terceros, excepto cuando sea necesario para procesar pagos o cumplir con la ley. En tales casos, garantizamos que sus datos estarán protegidos.</p>

            <h2>5. Seguridad de la Información</h2>
            <p>Tomamos medidas de seguridad razonables para proteger la información personal contra el acceso no autorizado, la alteración o la destrucción.</p>

            <h2>6. Derechos del Usuario</h2>
            <p>Usted tiene derecho a acceder, corregir o eliminar su información personal. Si desea hacerlo, puede contactarnos a través de los canales establecidos en esta página.</p>

            <h2>7. Cambios en la Política de Privacidad</h2>
            <p>Nos reservamos el derecho de modificar esta política de privacidad en cualquier momento. Las modificaciones se publicarán en esta página.</p>

        </section>
    </div>
</body>

{% endblock %}

pagina/app/templates/app/solicitar_cita.html
{% extends 'app/index.html' %}

{% block content %}
<div class="form-container">
    <h2>Solicitar una Cita</h2>
    <form method="post">
        {% csrf_token %}

        <label for="id_tatuador">Tatuador:</label>
        {{ form.tatuador }}
        
        {% if form.tatuador.errors %}
            <div class="error-message">
                {% for error in form.tatuador.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
        {% endif %}

        <label for="id_fecha">Fecha:</label>
        {{ form.fecha }}

        <label for="id_hora">Hora:</label>
        {{ form.hora }}
        
        <button type="submit" class="login-button">Solicitar Cita</button>
    </form>
</div>
{% endblock %}

pagina/app/templates/app/tatuadores.html
{% extends 'app/index.html' %}

{% block content %}

<!-- Contenedor Flex para alinear los elementos -->
<div class="contenedor">
    <h1 class="h1-form">Lista de Tatuadores</h1>

    {% if tatuadores %}
    <table class="tabla">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Especialidad</th>
                <th>Disponibilidad</th>
                <th>Teléfono</th>
                {% if user.is_superuser %}
                <th>Acciones</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for tatuador in tatuadores %}
            <tr>
                <td>{{ tatuador.nombre }}</td>
                <td>{{ tatuador.especialidad }}</td>
                <td>{{ tatuador.disponibilidad }}</td>
                <td>{{ tatuador.telefono }}</td>
                
                {% if user.is_superuser %}
                <td>
                    <a href="{% url 'editar_tatuador' tatuador_id=tatuador.tatuador_id %}" class="btn-editar">Editar</a>
                    <a href="{% url 'eliminar_tatuador' tatuador_id=tatuador.tatuador_id %}" class="btn-eliminar" 
                        onclick="return confirm('¿Estás seguro de que deseas eliminar a este tatuador?');">
                        Eliminar
                    </a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <p>No hay tatuadores registrados.</p>
    {% endif %}

    <!-- Botón Agregar Tatuador (colocado al final) -->
    {% if user.is_superuser %}
    <a href="{% url 'agregar_tatuador' %}" class="btn-agg">Agregar Tatuador</a>
    {% endif %}
</div>

{% endblock %}

pagina/app/templates/app/terminos.html
{% extends 'app/index.html' %}

{% block content %}
<body>
    <div class="container-terminos">

        <section>
            <h2>1. Aceptación de los Términos</h2>
            <p>Al utilizar los servicios de Perla Negra Ink, usted acepta estos Términos de Servicio y nuestra Política de Privacidad. Si no está de acuerdo con estos términos, por favor no utilice nuestros servicios.</p>

            <h2>2. Requisitos de Edad</h2>
            <p>Solo se permiten clientes mayores de 18 años para recibir un tatuaje. Si tiene menos de 18 años, deberá tener el consentimiento por escrito de un tutor legal para proceder con el tatuaje.</p>

            <h2>3. Consentimiento para el Tatuaje</h2>
            <p>Al recibir un tatuaje en Perla Negra Ink, usted confirma que no padece de ninguna condición médica que pueda poner en riesgo su salud o la de otros. El cliente entiende que un tatuaje es una intervención estética permanente.</p>

            <h2>4. Cuidado Posterior</h2>
            <p>Es responsabilidad del cliente seguir las instrucciones de cuidado posterior proporcionadas por el estudio para evitar infecciones o daños en el tatuaje.</p>

            <h2>5. Cancelaciones y Reembolsos</h2>
            <p>Si necesita cancelar o reprogramar su cita, debe hacerlo con al menos 48 horas de antelación. Los depósitos no son reembolsables.</p>

            <h2>6. Responsabilidad</h2>
            <p>Perla Negra Ink no será responsable de daños o lesiones que puedan ocurrir durante o después del tatuaje, siempre que se haya seguido correctamente el proceso de consentimiento informado y cuidado posterior.</p>

            <h2>7. Modificaciones a los Términos</h2>
            <p>Nos reservamos el derecho de modificar estos términos en cualquier momento. Cualquier cambio será publicado en esta página.</p>
        </section>
    </div>
</body>

{% endblock %}